### PR TITLE
fix: Disable debug in production

### LINKED ISSUE #767: Disable debug in production
https://app.asana.com/0/1204005227675382/1204038385197069/f

Currently the Django debug flag is true in the production environment, leading to security issues.

### PR DESCRIPTION
**Pull request by didrikmunther**
Fixes #767 by changing debug flag in the production settings file.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204038385197069
  - https://app.asana.com/0/0/1204053576959592

### CODE REVIEW

**Review by Nimejandro — DISMISSED** [review]

**Comment by Hampfh** [comment]
Porsev mentioned that this would bring some problems to the styles on the event page I think, have you tested the functionality of those pages are kept?

**Comment by Nimejandro** [comment]
> Porsev mentioned that this would bring some problems to the styles on the event page I think, have you tested the functionality of those pages are kept?

https://ais.armada.nu/api/events is currently empty but i could add a .catch on the axios command soon.
Try disabling it and adding something and see what happens

**Review by Hampfh — CHANGES_REQUESTED** [review]
To prevent this from being merged without addressing this I'll mark this as "request changes"

**Comment by didrikmunther** [comment]
Added `whitenoise` middleware, which should serve static files in production mode. Should resolve the problem.

**Review by Hampfh — APPROVED** [review]
Nice work!

**Pull request merged**
