### PR TITLE
Added warning about comment submission

### PR DESCRIPTION
**Pull request by walaro**

### CODE REVIEW

**Comment by macaullyjames** [comment]
Trying to check this locally but I had to create a fair, then I had to create a new recruitment period, then I had to create an application, but then there was no roles so I couldn't apply to anything and after that I gave up. Do you have a screenshot for the time being? :/

Yeah, we should fix this.

**Comment by purmonen** [comment]
Mac, we used to have import scripts and csv-files for that purpose

**Comment by walaro** [comment]
Please, it css, its basic css, can someone please approve this?

**Comment by macaullyjames** [comment]
@purmonen It might be a good idea to anonymise that data and add it back into the repo 🤔

**Comment by macaullyjames** [comment]
@walaro just post a screenshot.

**Comment by purmonen** [comment]
I get server error when merging. Mac, yes.

**Comment by macaullyjames** [comment]
@purmonen you need to review first :)

**Pull request merged**
