### PR TITLE
Changing from fugly favicon to super fly Armada logo.

### PR DESCRIPTION
**Pull request by svenanderzen**
Have only swapped the favicon from the black inverted armada logo to the same favicon as armada.nu.

### CODE REVIEW

**Comment by walaro** [comment]
I think the fugly favicon is a lot clearer then the alternative, I'm not just saying that because I made it with my own sweat and tears. :-) (But seriously, the circled one looks like ...., lets call it non-optimal... on my 1920*1080 screen, and its a fairly common resolution)

**Comment by svenanderzen** [comment]
Wow, this was most interesting. This is how the favicon looks like when viewing it in nautilus filebrowser but most importantly on the Chrome browser for Android... So it doesn't look good on mobile, hence I changed it. Didn't actually think that they'd render it differently? 

skarmbild fran 2016-10-19 22-08-19

**Comment by svenanderzen** [comment]
Otherwise I agree with you and I wouldn't have changed it :)

**Comment by walaro** [comment]
So I've just found this:
https://realfavicongenerator.net/blog/android-chrome-and-its-favicon/

Maybe we should generate an apple one, since chrome on android seems to fall back to it

**Comment by walaro** [comment]
if one were to run:
python manage.py runserver {{localip}}:{{port}}

Its possible to check out the changes from a device locally on the same network.

**Comment by purmonen** [comment]
On my Mac running Safari the favicon doesn't even resemble a Armada logo
screen shot 2016-10-20 at 13 19 58

**Comment by mictab** [comment]
The current one looks crappy on Chrome for macOS as well. Version 53.0.2785.143 (64-bit).

screen shot 2016-10-20 at 23 47 55

**Comment by walaro** [comment]
chrome_logo
This is what it looks like on windows 10 and linux

**Comment by mictab** [comment]
Well, https://realfavicongenerator.net/favicon_checker?protocol=https&site=ais.armada.nu#.WA0bOeF95HQ 

 ¯\\_(ツ)_/¯

**Pull request closed without merging**
