### PR TITLE
Implemented PUT request for /api/student_profile

### PR DESCRIPTION
**Pull request by Griffone**
Implemented a PUT request for url:
/api/student_profile?student_id=STUDENT_ID
and a json {"nickname":NICKNAME} file as payload

to test this:
* Either run python3 manage.py test api
* or make a PUT request yourself (I'm not sure how one would do that)

### CODE REVIEW

**Comment by Griffone** [comment]
Wait with the review, as I want to write an additional couple of tests, testing proper requests!

**Comment by Griffone** [comment]
Nevermind, I ran the tests and the methodology I used was fine

**Comment by emmabckstrm** [comment]
Looking at this

**Comment by emmabckstrm** [comment]
Docstring looks great but Travis fails. Maybe because the indentation with the docstring looks different from the other stuff in the model?

**Pull request merged**
