### PR TITLE
fix migration errors

### PR DESCRIPTION
**Pull request by jakobivarsson**
Well, hopefully this will fix the migration errors on the server.

### CODE REVIEW

**Comment by walaro** [comment]
I'm not sure its a good idea to rewrite the migrations like this

**Comment by jakobivarsson** [comment]
Probably not but this should fix the problem (the model is deleted in the migration after anyway)

**Comment by jakobivarsson** [comment]
We could also solve it by deleting all un-applied migrations and make them again.

**Comment by walaro** [comment]
Alright, since it has never been applied it will hopefully be fine

**Pull request merged**
