### PR TITLE
Homepage (rebased)

### PR DESCRIPTION
**Pull request by macaullyjames**
This is a duplicate of #43 by @svenanderzen rebased on top of the new `master`. Original description:

A first draft of a "homepage" for AIS? It even includes a "sailing" ship as the navbar-brand!

69f11a9c-77b1-11e6-93d4-0eaf78078083

### CODE REVIEW

**Comment by purmonen** [comment]
I like the beginning work on the front page, Sven!

We might want to keep it hidden until we get more stuff on it though so we don't confuse the user with two tabs with near duplicate information.

In that case we could make it accessible through the url but leave out the button that takes you there, just like with companies and events.

**Comment by mictab** [comment]
Nice, but that image of the ship is from last year's graphical profile. Should get a new one from our ADs :-)

**Comment by macaullyjames** [comment]
@svenneponken Mind if I delete the `homepage` branch (from #43) now? :)

**Comment by svenanderzen** [comment]
@macaullyjames Sweet! You sir, are a true hero, thanks for fixing everything! :) :+1: 

@mictab Know where we can find a new image? :)

**Comment by svenanderzen** [comment]
This is basically how this  years graphical profile would look like, haven't fiddled with the dimensions but imo it's not as good looking as last years. Graphics is not really my cup of tea so would appreciate some input form you guys. 

armada_2016

**Comment by mictab** [comment]
Still doesn't look right I believe. Ping @mfrisell @kyriaki93

**Comment by walaro** [comment]
I don't think we need branding, the navbar branding is more than enough, so we can probably just remove the image.

On a slightly more constructive note: What do you think about a two column layout instead of a single column?

**Comment by kyriaki93** [comment]
The image is from last year's graphical profile, but yeah I agree with Johannes. Skip the image and just use the white armada boat in the nav-bar :) The Armada boat looks rotated though

**Comment by svenanderzen** [comment]
Sorry for a slow reply, but I've removed the image from the startpage. It looks like this:

skarmbild fran 2016-09-21 20-15-34

A little empty, but I guess we'll get more there once we get events and other things going.

@walaro We tried with a two column layout but both me and @jakobivarsson thought it looked weird so we skipped it.

We also added a little CSS animation to the logo (on hover), to make the ship swing back and forth, please look at it if you think it should be there or removed before merging. :)

**Comment by svenanderzen** [comment]
I've added @Tisenos events to the homepage. Looks like this for the moment:

skarmbild fran 2016-10-05 21-24-21

I'll continue with adding the "I <3 my staff section" asap! :) In the mean time, maybe we can merge this if it doesn't all look like shit. :+1: <3

However, I still think that it looks kind of empty when it's lacking an image. What do everyone else think?

**Comment by svenanderzen** [comment]
@Tiseno thought that this was the way to go. So can we merge this now? If we should change more things i recommend that we bombard with issues, but still merge this so that we can at least have a working homepage for AIS. <3 

ais

**Pull request merged**
