### PR TITLE
Banquet flow

### PR DESCRIPTION
**Pull request by Griffone**
Created a banquet dummy flow.
Changed on_deletion behavior for BanquetTables to stop them from deleting banquetattendants.

To test:
* host server
* goto localhost:8000/fairs/2017/banquet/
* make sure you have at least 1 banquet attendant
* press the "sit attendants" button on the top
* if you don't see the button, log in on an account that has banquet.banquetattendant.can_sit_attendants permission or give the account one.
* make sure the attendants got sitted at tables. (Will use existing tables with correct sizes, or create new ones of size 8 as needed)

### CODE REVIEW

**Comment by Griffone** [comment]
Needs a permissions fix!!!

Don't review this PR positively if you see this comment and no follow up!

**Comment by emmabckstrm** [comment]
looking at this

**Comment by emmabckstrm** [comment]
Does it work in ais2?

**Comment by emmabckstrm** [comment]
My bad, I had not confirmed the attendant! :D

**Comment by hecan19** [comment]
could you resolve the conflicts @Griffone ? :) id like to start merging my stuff into the master and your code as soon as possible!

**Pull request merged**
