### PR TITLE
Added static root

### PR DESCRIPTION
**Pull request by walaro**
Static_dirs are used for additional static files

### CODE REVIEW

**Comment by macaullyjames** [comment]
So what does this do exactly? 😁

**Comment by walaro** [comment]
It adds a static_root, so that i can perform a collectstatic, which I cant do now.
static_root and static_dirs are the same thing, you are suppose to have a static_root and then if you need more static locations, you put them in static_dirs. Atleast that's what i read in the documentation. That PR is going to be fairly substantial, so I'm splitting them.

**Comment by macaullyjames** [comment]
But isn't the static root already served by nginx? https://github.com/armada-ths/ais/blob/a4986d5618dfdb9cacb52a1d57200c72e4a50b1f/ais_nginx.conf#L31-L33

**Comment by walaro** [comment]
Yes, the static files are served by nginx in production, that's done by the STATIC_URL, being /static/, so nginx catches all references to static material, and serves them. If you removed the nginx static serving, it would instead be served by python/django from the STATIC_ROOT, or STATIC_DIR.
So the STATIC_ROOT and STATIC_DIR are suppose to do the samething, but i cant collect the static files without a defined STATIC_ROOT

**Comment by macaullyjames** [comment]
So why do you need to collect the files if they're already being served? What is it you want to do? :)

**Comment by walaro** [comment]
Because they change over time

**Comment by macaullyjames** [comment]
But what is it you want to do with them? 😭

**Comment by walaro** [comment]
https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/

**Comment by macaullyjames** [comment]
I understand _what_ you're doing, I just don't get _why_ you're doing it. We already serve static files efficiently (?) don't we? :)

**Comment by walaro** [comment]
It has nothing to do with the serving of the files

**Pull request merged**
