### PR TITLE
Table view

### PR DESCRIPTION
**Pull request by worldyn**
A table placement view with very basic design

Test: go to fairs/2017/banquet/placement
Should be redirected to banquet signup if not logged in / if user does not have an attendant
Add other attendants to same table in order to see 'table mates'.

### CODE REVIEW

**Comment by Griffone** [comment]
I'm reviewing this

**Comment by Griffone** [comment]
Oh and tests ran, and I made a local merge into master and it also worked fine.

**Comment by Griffone** [comment]
image

Although I am confirmed in the database

**Comment by emmabckstrm** [comment]
@worldyn  This needs to be closed an reopened in order for travis to run

**Pull request closed without merging**
